#!/bin/zsh

_ActivityIndicator2 () {
	ARR_PHASES=('|' '/' '-' '\\')
	IDX=1
	export CONT=true
	while ${CONT}
	do
		LINE="${2}${ARR_PHASES[$((IDX++))]}${3}"
        echo -n "$(repeat-char ${#LINE} '\b')${LINE}"
		sleep ${1:-0.5}
		[[ ${IDX} -gt 4 ]] && IDX=1
	done
}

_ActivityIndicator2 ${@}
