#!/bin/zsh


_add-foldername () {
    VARNAME="FOLDERNAME_$(uppercase ${1// /_})"
	FOLDERNAME="${VARNAME}=" 
	RES=$(cat $SHELL_VARS | grep $FOLDERNAME) 
	[[ -n $RES ]] && { echo "$FOLDERNAME already exists"; return 321; }
	CMD_ADDFOLDERNAME="addvar ${VARNAME} \"${1}\"" 
	eval $CMD_ADDFOLDERNAME
}
_add-foldername ${@}
