#!/bin/zsh


_add-unicode-chars () {
	FROM="${1}"
    TO="${2}"
    OPTS=()
    [[ -n ${3} ]] && {
        OPTS+='-t'
            OPTS+="${3}"
        }
    ARR_AB=() 
	for i in {A..Z}
	do
		ARR_AB+=${i} 
	done
	IDX=1 
	for uc in {${FROM}..${TO}}
	do
		HEX=$(convert-number -x $uc) 
		[[ $#FROM -gt 4 ]] && U="U"  || U="u" 
		source addvar ${OPTS} UNICODE_${3}_${ARR_AB[$IDX]} ${HEX//0x/${U}}
		((IDX++))
	done
}
_add-unicode-chars ${@}
