#!/bin/zsh

if [ $# -eq 0 ] ||  [ $# -lt 3 ]; then
    echo "$# is $((3-$#)) too few"
    echo "Usage: $(basename $0) example.com username chiffre"
    exit 1
fi

UNUTMA_FILE="${1}"
shift

if [ -e "$HOME/unutmalist/${UNUTMA_FILE}.txt" ]; then
    echo "" >> "$HOME/unutmalist/${UNUTMA_FILE}.txt"
fi


echo "$1" >> "$HOME/unutmalist/${UNUTMA_FILE}.txt"
shift
echo -n "$1" >> "$HOME/unutmalist/${UNUTMA_FILE}.txt"
shift
echo "\$# = ${#}"

if [[ $# -gt 0  ]]
then
    echo "_${@}" | sed -e "s/ //g" >> "$HOME/unutmalist/${UNUTMA_FILE}.txt"
    unutmabunu ${UNUTMA_FILE} ${@}
else
    read IT
    [[ -n ${IT} ]] && unutmabunu ${UNUTMA_FILE} ${IT}
fi

echo "" >> "$HOME/unutmalist/${UNUTMA_FILE}.txt"
