#!/bin/zsh

if startsWithDash ${1} && 
    [ ${1//-/} = 'b' -o ${1//-/} = 'browser' ] && 
    [[ -d "${APPLICATIONS}/$(capitalcase ${2}).app" ]]
then 
    CURR_BROWSER="$(capitalcase ${2})"
    shift 2
fi

PIPE_INPUT=$(get-stdin &)

[[ -z ${PIPE_INPUT} ]] && URL="${1:-$(pbpaste)}"

#if [[ -z $URL ]] || (! startsWith ${URL} 'http' && ! startsWith ${URL} 'file')
#then
#    INPUT_PIPE="$(cat < /dev/stdin)"
#    [[ -n ${INPUT_PIPE} ]] && URL="${INPUT_PIPE}"
#fi

open -a "/Applications/${CURR_BROWSER:-Google Chrome}.app" "${URL}"

