#!/bin/zsh
OPTS=()
TMPINPUT="${1}"

[[ ${#} -gt 0 ]] && startsWithDash ${TMPINPUT} && [[ ${TMPINPUT[2]} = 'c' ]] && echo ${#ARROWDBL} && . rts 0
[[ ${#} -gt 0 ]] && startsWithDash ${TMPINPUT} && [[ ${TMPINPUT[2]} =~ '[^0-9]' ]] && OPTS+="${1}" && shift

_char-arrow-double () {
	[[ ${#} -eq 0 ]] && { echo ${OPTS} ${ARROWDBL}; . rts 0 }
    for IDX in ${@}
    do
	    isNumeric ${IDX} && [[ ${IDX} -le ${#ARROWDBL} ]] && echo ${OPTS} ${ARROWDBL[${IDX}]} || echo ${OPTS} ${IDX}
    done
}
_char-arrow-double ${@}
