#!/bin/zsh
OPTS=()
TMPINPUT="${1}"

[[ ${#} -gt 0 ]] && startsWithDash ${TMPINPUT} && [[ ${TMPINPUT[2]} = 'c' ]] && echo ${#SZ_ARROW_L} && . rts 0
[[ ${#} -gt 0 ]] && startsWithDash ${TMPINPUT} && [[ ${TMPINPUT[2]} =~ '[^0-9]' ]] && OPTS+="${1}" && shift

_char-arrow-left () {
	[[ ${#} -eq 0 ]] && { echo ${OPTS} ${SZ_ARROW_L}; . rts 0 }
    for IDX in ${@}
    do
	    isNumeric ${IDX} && [[ ${IDX} -le ${#SZ_ARROW_L} ]] && echo ${OPTS} ${SZ_ARROW_L[${IDX}]} || echo ${OPTS} ${IDX}
    done
}
_char-arrow-left ${@}
