#!/bin/bash

#ffmpeg -fflags +genpts -i "$1" -r 24 $(filename "$(fileroot "$1").mp4")

IN="$1"
EXT=$(fileext "$IN")
TO_TYPE=mp4
[[ -n "$2" ]] && TO_TYPE="$2"
OUT=${IN//$EXT/$TO_TYPE}

ffmpeg -fflags +genpts -i "$IN" -r 24 "$OUT"
