#!/bin/zsh


_code_ () {
	[[ ${#} -eq 1 ]] && [[ -n ${1} ]] && [[ -d "${1}" ]] && {
        [[ ${1} = '.' ]] && setvar -t ${SHELL_VARS_PROJECTS} PROJECTS_LATEST "${PWD}" ||  setvar -t ${SHELL_VARS_PROJECTS} PROJECTS_LATEST "${1}" 
    }
	source ${SHELL_VARS_PROJECTS}
    [[ ${#} -eq 0 ]] && original code ${PROJECTS_LATEST} || original code $@
}
_code_ ${@}
