#!/bin/zsh

CAT1=ccat
CAT2=ccat
SHOW_PATHNAME=false
STRIP_COMMENTS=false

[[ -e "$(which ccat)" ]] || { CAT1=cat; CAT2=cat }
if startsWithDash ${1}
then
    [ ${1/-/} = 's' -o ${1/-/} = '-strip-comments' ] && STRIP_COMMENTS=true && shift
    [ ${1/-/} = 'n' -o ${1/-/} = '-number' ] && CAT1='cat' && OPTS='-n' && shift
    [ ${1/-/} = 'p' -o ${1/-/} = '-pathname' ] && SHOW_PATHNAME=true && shift
fi

_cs_() {
    PATH_COMMAND=($(which -a "${1}" | egrep '^/.*' ))

    CNTR=0
    for cmd in ${PATH_COMMAND}
    do
        ${SHOW_PATHNAME} && ecko "\n$((++CNTR)): ${cmd}" 10 199
        if isShellScript "${cmd}" 
        then
            ${STRIP_COMMENTS} && 
                ${CAT1} ${OPTS} ${cmd} | sed -E "s/(^[ ]*|[^\$\{])#[^\!].*/${SUBSTITUTE_CHARS}/g" | ${CAT2} || 
                ${CAT1} ${OPTS} ${cmd} | ${CAT2}
        fi
    done
}

_cs_ ${@}
