#!/bin/zsh

IDX=0

_contains-link () {
	for p in ${@}
	do
        ((IDX++))
		if startsWith $p http 
        then 
            echo ${IDX}
            true
            return #break 
        fi
	done
    false
}
_contains-link ${@}
