#!/bin/zsh
LLINK=$(basename $1).desktop

if [ -n "$2" ]; then
    IFS='/' read -r -A array <<< "$2"
    if [ ${#array[@]} -gt 2 ] && ! [ -d "$(dirname $2)" ]; then
        mkdir -p "$(dirname $2)"
    fi
fi

if [ -n "$2" ] && [ -d "$2" ]; then
    LLINK="$2/$LLINK"
elif [ -n "$2" ]; then
    LLINK="$2.desktop"
fi

echo "[InternetShortcut]"
echo $LLINK
PROTOCOL=$(grep -o 'https://\|http://' <<< $1)
                                #echo "Protocol PRE : "$PROTOCOL
if [ -z "$PROTOCOL" ]; then
	PROTOCOL=http://
else
	PROTOCOL=''
fi
                                #echo "Protocol POST : "$PROTOCOL
read -d '' WEBLOC <<EOF
[Desktop Entry]
Encoding=UTF-8
Name=[LLINK]
Type=Link
URL=[URL]
Icon=text-html
EOF
echo "$LLINK"
WEBLOC=${WEBLOC/\[LLINK\]/$LLINK}
echo ${WEBLOC/\[URL\]/$PROTOCOL$1} > "$LLINK"

