#!/bin/bash
URL="${1}"
LLINK=$(basename $URL).url
#LLINK=${LLINK//[^a-zA-Z\d\s.]/_}

if [ -n "$2" ]; then
    IFS='/' read -r -a array <<< "$2"
    if [ ${#array[@]} -gt 2 ] && ! [ -d "$(dirname $2)" ]; then
        mkdir -p "$(dirname $2)"
    fi
fi

if [ -n "$2" ] && [ -d "$2" ]; then
    LLINK="$2/$LLINK"
elif [ -n "$2" ]; then
    LLINK="$2.url"
fi

echo "[InternetShortcut]" > $LLINK
echo $LLINK

PROTOCOL=$(grep -o 'https://\|http://' <<< $1)
if [ -z "$PROTOCOL" ]; then
	PROTOCOL=http://
else
	PROTOCOL=''
fi

#if [ -n "$2" ]; then
#    cd "$2"
#fi

echo URL=${PROTOCOL}${1} >> $LLINK

#if [ -d "$2" ]; then
#    cd "$OLDPWD"
#fi
