#!/bin/bash
if [ -n "$2" ]; then
    LLINK=$(basename $1).webloc
    LLINK=${LLINK//[^a-zA-Z\d\s.]/_}
else
    LLINK="$2.webloc"
fi

echo [InternetShortcut]
echo "FILE $LLINK"

PROTOCOL=$(grep -o 'https://\|http://' <<< $1)
                                #echo "Protocol PRE : "$PROTOCOL
if [ -z "$PROTOCOL" ]; then
	PROTOCOL=http://
else
	PROTOCOL=''
fi
                                #echo "Protocol POST : "$PROTOCOL
read -d '' WEBLOC <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>URL</key>
        <string>[URL]</string>
    </dict>
</plist>
EOF

echo ${WEBLOC/\[URL\]/$PROTOCOL$1} > $LLINK

