#!/bin/bash
LLINK=$(basename $1).url
LLINK=${LLINK//[^a-zA-Z.]/_}
echo [InternetShortcut]
echo $LLINK
PROTOCOL=$(grep -o 'https://\|http://' <<< $1)
#echo "Protocol PRE : "$PROTOCOL
if [ -z $PROTOCOL ]; then
	PROTOCOL=http://
else
	PROTOCOL=''
fi

if [ -n "$2" ]; then
    cd "$2"
fi

#echo "Protocol POST : "$PROTOCOL
echo URL=$PROTOCOL$1 >> $LLINK

 if [ -n "$2" ]; then
     cd "$OLDPWD"
 fi
