#!/bin/zsh

curl -V

source ${SHELL_VARS_OUTPUT}
URL="${@[-1]}"
LIBCURL=(--libcurl ${OUTPUT_CURL}/getfile-${URL##*/}-$(date +%s).c)

curl__ () {
	contains-link ${@} && curl ${LIBCURL} ${@} || curl ${LIBCURL} ${@} $(pbpaste) -O
}
curl__ ${@}
