#!/bin/bash
PATHNAME=$(dirname $1)
FOLDERNAME=$(basename $1)
cd $PATHNAME
gpg -d $FOLDERNAME > "tmp_${FOLDERNAME}"
mv "tmp_${FOLDERNAME}" $FOLDERNAME
tar -tzf $1 &> /dev/null

if [ $? -eq 0 ]; then 
	tar -xzf $1 &> /dev/null; 
	rm $1;
fi

