#!/bin/zsh

[[ -z ${IFS_PREV} ]] && IFS_PREV=()
IFS_PREV+=${IFS}
IFS=${DELIMITER_ENDL}
INPUT_STDIN=($(get-stdin &))

_ecko() {

    BOLD='%b'
    NL=$'\n'
    KF='%k%f'

    CNTR=0

    for param in ${@}
    do
        #echo "Begin param:${param}: CNTR: ${CNTR}"
        if startsWithDash ${param}
        then
            ([[ ${param/-/} = "-bold" ]] || [[ ${param/-/} = "b" ]]) && BOLD='%B' && ((CNTR++)) #&& echo bold
            ([[ ${param/-/} = "-newline" ]] || [[ ${param/-/} = "n" ]]) && NL='' && ((CNTR++)) #&& echo newline
        else
            ([[ CNTR -ge 0 ]] && [[ CNTR -le 2 ]]) && [[ -z "${TEXT}" ]] && TEXT="${param}"  && ((CNTR++)) #&& echo text
        fi
        #echo "end param:${param}: CNTR: ${CNTR}"
    done
#echo "All:${@}"
#echo "BOLD:${BOLD}"
#echo "NL:${NL}"
#echo "TEXT:${TEXT}"
    shift ${CNTR}
#echo "All after shift:${@}"

    FGC=''
    BGC=''

    #if isNumeric ${1}
    #then
	#    TEXT="$(cat < /dev/stdin)"
    #else
#	    TEXT="${1}"
#    	shift
    #fi


    [[ -n ${1} ]] && isNumeric ${1} && FGC="%F{${1}}"
    [[ -n ${2} ]] && isNumeric ${2} && BGC="%K{${2}}"
    [[ -n ${3} ]] && isNumeric ${3} && KF=''

    print -Pn "${FGC}${BGC}${BOLD}${TEXT}${KF}" ${NL} #  > /dev/stdin
}

if [[ -n ${INPUT_STDIN} ]]
then
    for line in ${INPUT_STDIN}
    do
        _ecko ${line} ${@}
    done
else
    _ecko ${@}
fi


