ekko () {
	PTEXT="${1}"
	isDebug && echo $PTEXT
	COLORBG=003
	COLORFG=000


	isDebug && echo $COLORBG
	isDebug && echo $COLORFG

	RESULT_OUTPUT="$BG[$COLORBG]$FG[$COLORFG]${PTEXT}"
	#RESULT_OUTPUT="$FG[$COLORFG]$BG[$COLORBG]${PTEXT}"
	RESULT_OUTPUT=${RESULT_OUTPUT//\%/}
	RESULT_OUTPUT=${RESULT_OUTPUT//\{/}
	RESULT_OUTPUT=${RESULT_OUTPUT//\}/}
	echo $RESULT_OUTPUT
}