#!/bin/zsh

IFS=${DELIMITER_ENDL}

_filename() {
    echo "${1}" | rev  | cut -d '/' -f1  | rev
}
isDebug && echo ${@}

if [[ ${#} -gt 0 ]]
then
    local CNT=0
    for TMP_PATH in "${@}"
    do
        isDebug && echo "Pfad Nr.$((CNT+=1)) ${TMP_PATH}"
        ARR_PATH=("${TMP_PATH}")
    done
else
    INPUT_PIPE="$(cat < /dev/stdin)"
    [[ -n ${INPUT_PIPE} ]] && ARR_PATH=($(echo ${INPUT_PIPE}))
fi

for currPath in ${ARR_PATH}
do
    _filename ${currPath}
done


