#!/bin/zsh

OPTS=()
[[ ${#} -gt 0 ]] && startsWithDash ${1} && OPTS+="${1}" && shift

IDX=${1:-}

 #. ${SHELL_VARS}
 . fingeru # This is far more performant than sourcing the complete set of exported variables again.

[[ ${IDX} -gt ${#ARR_FINGERUP} ]] && . rts 69 #${SHLVL}

_finger-up () {
#	echo ${OPTS} ${ARR_FINGERUP[${1:-1}]}
    [[ ${#} -gt 0 ]] && echo ${OPTS} ${ARR_FINGERUP[${1}]} || echo ${ARR_FINGERUP[@]}
}
_finger-up ${@}


# PS: why aren't exported arrays not available in scripts as the other variable are

