#!/bin/zsh

ARR_PDF_VARS_NAME=($(get-pdf-vars-name))

mkdir -p ${TMP_HASH}/PDF-Dirs

_get-all-pdfs-of-pdf-vars () {
	for dir in $ARR_PDF_VARS_NAME
	do
		TRGT_PATH=${TMP_HASH}/PDF-Dirs/pdf_dir-${dir}.txt 
		cmd="ls -lFG \$${dir}/**/*.pdf 2>> ${TMP_HASH}/PDF-Dirs/pdf-dir-error.txt" 
		echo ${cmd} | tee -a ${TRGT_PATH}
		eval ${cmd} | tee -a ${TRGT_PATH}
	done
    tail -n +1 ${TMP_HASH}/PDF-Dirs/pdf_dir-* | grep -oE "(\/Users.*|==.*|ls.*)" > ${TMP_HASH}/PDF-Dirs/catt-pdf_dir-filenames-only.txt  #${TMP_HASH}/PDF-Dirs/pdf_dir-* | sed -E "s/.*sedatkilinc.*([0-9]{2}:[0-9]{2}|[0-9]{4}) //g" > ${TMP_HASH}/PDF-Dirs/catt-pdf_dir-filenames-only.txt

    cat ${TMP_HASH}/PDF-Dirs/catt-pdf_dir-filenames-only.txt | grep -E 'pdf$' | pbcopy
    pbwrite ${TMP_HASH}/PDF-Dirs/PDFs.csv
}
_get-all-pdfs-of-pdf-vars ${@}
