#!/bin/zsh

TARGET=$PWD
SIZE="G"
if [[ -d "${1}" ]]
then
    TARGET="${1}"
    shift
fi
if [ -n "${1}" ] && 
    ([ "${1}" = "B" ] || [ "${1}" = "K" ] || [ "${1}" = "M" ] || [ "${1}" = "G" ]); then
    SIZE=${1}
fi
TARGET=${TARGET// /\\ }
CMD="du -sh  $TARGET/* | grep -E \"\d{1,},?\d?$SIZE\""
echo $CMD
eval $CMD | tee "${OUTPUT_DISKUSAGE}/$(path2string -n ${TARGET})_$(date +%s).txt"
