#!/usr/bin/env php

<?php
if (count($argv) > 1) {
    $url=$argv[1];
//var_dump(parse_url($url, PHP_URL_HOST));
    echo parse_url($url, PHP_URL_HOST)."\n";
    //echo "hallo";
}

/*
print_r($argv);
$url=$argv[1];
// $url='http://benutzername:passwort@google.de:9090/pfad?argument=wert#textanker'
print_r(parse_url($url));
var_dump(parse_url($url, PHP_URL_SCHEME));
var_dump(parse_url($url, PHP_URL_USER));
var_dump(parse_url($url, PHP_URL_PASS));
var_dump(parse_url($url, PHP_URL_HOST));
var_dump(parse_url($url, PHP_URL_PORT));
var_dump(parse_url($url, PHP_URL_PATH));
var_dump(parse_url($url, PHP_URL_QUERY));
var_dump(parse_url($url, PHP_URL_FRAGMENT));
 */
?>
