#!/bin/zsh

BOOKMARK_FILE="$1"

EXT=$(fileext $BOOKMARK_FILE)

if [ $# -gt 1 ]; then
    BOOKMARK_FILE="$2"
    OPTION="$1"
fi

if [ $EXT = "url" ]; then
    URL=$(cat $BOOKMARK_FILE | cut -d "=" -f2)
else
    URL_NODE=$(cat "$BOOKMARK_FILE" | grep -E '<.+string>')

    URL1=${URL_NODE//<string>/ }
    URL2=${URL1//<\/string>/ }
    URL=${URL2// /}
fi

echo $OPTION $URL

