#!/bin/zsh

IFS=${DELIMITER_ENDL}

_getYTID () {
	FN="${1##*/}" 
	FN="$(fileroot ${FN})" 
	[[ $FN[-12] = '-' ]] && echo $FN[$((${#FN}-10)),-1]
}

if [[ $# -eq 0 ]]
then
    INPUT_STDIN=($({ get-stdin | sed -E "s/\/[  ]*$//g" } &))
fi
    
for fo in ${INPUT_STDIN:-${@}}
do
    _getYTID "${fo}"
done

