#!/bin/zsh

[[ -d "${HOME}/.gdrive-excludes/$(path2string -b '[SPACE]' ${PWD})" ]] || { echo "Kein Git-Repo, amigo"; exit 1;  }
# echo "ln -s \"${HOME}/.gdrive-excludes/$(path2string -b '[SPACE]' ${PWD})\" .git"
ln -s "${HOME}/.gdrive-excludes/$(path2string -b '[SPACE]' ${PWD})" .git

_gitt () {
    #echo "ln -s \"${HOME}/.gdrive-excludes/$(path2string -b '[SPACE]' ${PWD})\" .git"
    git ${@}
    rm -f .git
}
_gitt ${@}
