#!/bin/zsh

# REGEX to grep file name in the result output using `less`
# of shape:  ./path/to/file.js:12:
#  ^\..*:[0-9]\+:   
# of shape:  /User/username/project/path/to/file.js:12:
#  ^\/.*:[0-9]\+:   
# or for both type  just 
# .*:[0-9]\+:
# for grep -E in command line don't escape '+'

TMP_EXCLUDES=()
startsWithDash ${1} && [ ${1/-/} = 't' -o ${1/-/} = '-total-excludes' ] && TMP_EXCLUDES=(${GREP_EXCLUDES}) && shift

OPTS='-nIRS'
startsWithDash ${1} && [ ${1/-/} = 'k' -o ${1/-/} = '-kill-opts' ] && OPTS='' && shift

_grep-folder () {
	ecko "\${TMP_EXCLUDES} ${TMP_EXCLUDES}" 118 88 > /dev/stdin
	ecko "\${OPTS} ${OPTS}" 118 88 > /dev/stdin
	ecko "\${@} ${@}" 118 88 > /dev/stdin
	ecko "grep  --exclude-dir '\.git' ${TMP_EXCLUDES} --color=auto ${OPTS} ${@}" 188 88 > /dev/stdin
	grep --color=auto --exclude-dir '\.git' ${TMP_EXCLUDES} --color=auto ${OPTS} ${@}
}

isDebug && _grep-folder ${@} || _grep-folder ${@} 2> /dev/null

