#!/bin/bash
USER=`whoami`
while getopts u:g: OPTION
do
	case "$OPTION"
	in
		u)USER=$OPTARG;;
		g)GROUP=$OPTARG;;
	esac
done
#echo -n "$USER "
OUTPUT=$(dsmemberutil checkmembership -U $USER -G $GROUP)
echo "${OUTPUT/user/$USER}"
