#!/bin/bash

ERR_CNT=0
i=1
sbst=$2

TMP=$1".tmp"
cp $1 $TMP
while read line
do
    echo $i $line
    CMD=$(echo ${sbst//\[URL\]/$line})
    echo "command $CMD"
    eval $CMD
    if [ $? -eq 0 ]; then
        replace $line "" $TMP
        [ $# -eq 3 ] && echo $line >> $3
    fi
    ERR_CNT=$((ERR_CNT+$?))
    echo "Error count $ERR_CNT "
    i=$((i+1))
done < $1

if [ $ERR_CNT -eq 0 ]; then
    mv $1 ~/.Trash;
    touch $1;
else
    mv $TMP $1
fi

# example call
# handlefile2 2download.txt 'echo [URL]; echo $(echo [URL] | cut -d"=" -f2)'
