#!/bin/zsh

CURR_SHELL_ALIASES="${SHELL_ALIASES}"
[[ ${#} -gt 0 ]] && startsWithDash ${1} && [ ${1/-/} = 't' -o ${1/-/} = '-target' ] && [[ -w "${2}" ]] && CURR_SHELL_ALIASES="${2}" && shift 2

[[ -n ${1} ]] && COUNT_ENTRIES="-n ${1}"

tail ${COUNT_ENTRIES} "${CURR_SHELL_ALIASES}"

