#!/bin/zsh

ISDEBUG=$(which isDebug | wc -l)

NUMBERALIASES=$(alias | wc -l)

[[ $ISDEBUG -eq 1  ]] && source $BASHDEBUGSTATE
[[ $NUMBERALIASES -lt 3  ]] && source ~/.bash_aliases

INPUT="$1"

IFS=$','

if [ -n "$2" ]; then
    IFS="$2"
fi

for i in $(echo $INPUT); do 
    echo $i; 
done 
#unset IFS
resetIFS
