#!/bin/bash


# create dummy input lines (think output of say, ls)
read -d '' INPUT_LINES <<EOF
/path/to/first file
/path/to/second file
/path/to/third file
EOF

INPUT_LINES=$1

# without IFS
for item in $(echo "$INPUT_LINES"); do
	echo "$item"
done

echo


# with IFS
IFS=$':'
for item in $(echo "$INPUT_LINES"); do
	echo "$item"
done

# reset back to default value
unset IFS
