#!/bin/zsh

ISDEBUG=$(which isDebug | wc -l)

NUMBERALIASES=$(alias | wc -l)

[[ $ISDEBUG -eq 1  ]] && source $BASHDEBUGSTATE
[[ ${NUMBERALIASES} -lt 3  ]] && [[ -n ${SHELL_ALIASES} ]]  && [[ -r ${SHELL_ALIASES} ]] && source ${SHELL_ALIASES}
NUMBERALIASES=$(alias | wc -l)
[[ ${NUMBERALIASES} -lt 3  ]] && [[ -r ~/.shell_aliases ]] && source ~/.shell_aliases

INPUT="$1"
IFS_ORIG=${IFS}
IFS=$','

if [ -n "$2" ]; then
    IFS="$2"
fi

for i in $(echo $INPUT); do 
    echo $i; 
done 
#unset IFS
resetIFS
IFS=${IFS_ORIG}
