#!/bin/zsh

#OPTION=o

#[[ -n ${1} ]] && { OPTION="${1}"; shift }

#env | grep -${OPTION}E "LINKS_[A-Z]*[_A-Z]*"
#env | grep -${OPTION}E "^LINKS(_[0-9A-Z]*)*" ${@}
env | grep -E "^LINKS_[-_0-9A-Z]*" -$(echo ${@} | sed -e 's/[- ]*//g')
