#!/usr/bin/env python3

import sys
import math

def square_root(num):
    return math.sqrt(num)

def log2n(num):
    return math.log2(num)

def handleInput(operation, params) :
    
    match(operation):
        case 'sqrt': 
            return square_root(float(params[2]))
        case 'log2':
            return log2n(float(params[2]))



if __name__ == '__main__' :
    EXIT_CODE = 0
    if len(sys.argv) > 2 :
        #print(len(sys.argv), sys.argv.slice(1))
        print(handleInput(sys.argv[1], sys.argv))
    else :
        EXIT_CODE = 1

    sys.exit(EXIT_CODE)

