#!/bin/zsh

if [ $# -eq 0 ]; then
    echo "arguments missing"
    echo "Usage: $(basename $0) example.com"
    exit 1
fi
/Applications/Firefox\ Developer\ Edition.app/Contents/MacOS/firefox "https://noscript.net/about/$1\;$1"
