#!/bin/zsh


len=$(echo ${1} | wc -c)
len=$(( $len - 1 ))
 
for (( i=1; i<=$len; i++ ))
do
   # get one digit at a time
    digit=$(echo ${1} | cut -c $i)
   # use case control structure to find digit equivalent in words 
    case $digit in
        0) echo -n "zero " ;;
        1) echo -n "one " ;;
        2) echo -n "two " ;;
        3) echo -n "three " ;;
        4) echo -n "four " ;;
        5) echo -n "five " ;;
        6) echo -n "six " ;;
        7) echo -n "seven " ;;
        8) echo -n "eight " ;;
        9) echo -n "nine " ;;
    esac	
done
 
# just print a new line
echo ""
