#!/bin/zsh

char-digit-super -n ${UC_SUPER_PARANTHESIS_LEFT} ${@} ${UC_SUPER_PARANTHESIS_RIGHT}

#_number-paranthesis-super () {
	#SZ_FORMAT="echo -n \${UC_SUPER_PARANTHESIS_LEFT}\${UC_SUPER_${1}}\${UC_SUPER_PARANTHESIS_RIGHT}" 
	#isDebug && echo "${SZ_FORMAT}" > /dev/stdin 
	#eval "${SZ_FORMAT}"
#}
#_number-paranthesis-super ${1}
