#!/bin/zsh

local SUBST=${SLASH_DIVISION}
local SUBST_SPACE='-'

CNT=0

while getopts s:b: OPTION
do
    case "$OPTION"  
    in             
        s)          
            SUBST=$OPTARG
            ((CNT+=2))
            ;;
        b)
            SUBST_SPACE=$OPTARG
            ((CNT+=2))
            ;;                      
    esac        
done

shift ${CNT}

_path2string () {
	local ARG_PATH="${1}"
    [[ "${ARG_PATH[-1]}" = '/' ]] && ARG_PATH=${ARG_PATH[1,-2]}
	[[ $ARG_PATH[1] = '/' ]] && 
        ARG_PATH=${ARG_PATH[2,$#ARG_PATH]//\//${SUBST}} || 
        ARG_PATH=${ARG_PATH//\//${SUBST}}
    echo ${ARG_PATH// /${SUBST_SPACE}}
    #echo $ARG_PATH 
}
_path2string ${@}
