#!/bin/zsh

ADD=false

startsWithDash ${1} && [ ${1//-/} = 'a' -o ${1//-/} = 'add' ] && ADD=true && shift
startsWithDash ${1} && [ ${1//-/} = 'm' -o ${1//-/} = 'mkdir' ] && mkdir -p "$(dirname ${2})" && shift

case "${ADD}"
    in
    true)
        pbpaste >> ${1};     
        echo >> ${1};
        ;;
    *)
        mkdir -p "$(dirname ${1})"
        pbpaste > ${1};
        echo >> ${1};
        ;;
esac
