#!/bin/zsh

ADD=false
IS_FIRST=false
IS_LAST=true
COMPLETE_ROWS=false
SHIFT=0
for param in ${@}
do
    startsWithDash ${param} && [ ${param//-/} = 'a' -o ${param//-/} = 'add' ] && ADD=true && ((SHIFT++))
    startsWithDash ${param} && [ ${param//-/} = 'm' -o ${param//-/} = 'mkdir' ] && mkdir -p "$(dirname ${2})" && ((SHIFT++))
    startsWithDash ${param} && [ ${param//-/} = 'f' -o ${param/-/} = '-first' ] && IS_FIRST=true && ((SHIFT++))
    startsWithDash ${param} && [ ${param//-/} = 'n' -o ${param/-/} = '-not-last' ] && IS_LAST=false && ((SHIFT++))
    startsWithDash ${param} && [ ${param//-/} = 'r' -o ${param/-/} = '-row' ] && COMPLETE_ROWS=true && ((SHIFT++))
 #   ecko "SHIFT=${SHIFT}"
done
shift ${SHIFT}
TARGET_FILE="${1}"

EXT=$(fileext ${TARGET_FILE})
#echo "EXT=${EXT} • TARGET_FILE =${TARGET_FILE} • ADD=${ADD} • IS_FIRST=${IS_FIRST} • IS_LAST=${IS_LAST}";
case "${ADD}"
    in
    true)
        ${IS_FIRST} && echo >> ${TARGET_FILE};
        ! [[ ${EXT} = 'csv' ]] && [[ -w "${TARGET_FILE}" ]] && add-horizontal-separator "${TARGET_FILE}"
        pbpaste >> ${TARGET_FILE};     
        ${IS_LAST} && echo >> ${TARGET_FILE} || echo -n ','  >> ${TARGET_FILE};
        #echo "add";
        ;;
    *)
        mkdir -p "$(dirname ${TARGET_FILE})"
        pbpaste > ${TARGET_FILE};
        ${IS_LAST} && echo >> ${TARGET_FILE} || echo -n ','  >> ${TARGET_FILE};
        #echo "else";
        ;;
esac

if [[ ${EXT} = 'csv' ]] && ! $COMPLETE_ROWS
then
    TMPCSV=$(replace-commas "${TARGET_FILE}")
    TMPCSV=$(replace-dblquotes "${TMPCSV}")
    mv "${TMPCSV}" "${TARGET_FILE}"
fi
