#!/bin/zsh

ADD=false
IS_FIRST=false
IS_LAST=true
startsWithDash ${1} && [ ${1//-/} = 'a' -o ${1//-/} = 'add' ] && ADD=true && shift
startsWithDash ${1} && [ ${1//-/} = 'm' -o ${1//-/} = 'mkdir' ] && mkdir -p "$(dirname ${2})" && shift
startsWithDash ${1} && [ ${1//-/} = 'f' -o ${1/-/} = '-first' ] && IS_FIRST=true && shift
startsWithDash ${1} && [ ${1//-/} = 'n' -o ${1/-/} = '-not-last' ] && IS_LAST=false && shift

TARGET_FILE="${1}"

EXT=$(fileext ${TARGET_FILE})
echo EXT=$EXT;
case "${ADD}"
    in
    true)
        ${IS_FIRST} && echo >> ${TARGET_FILE};
        pbpaste >> ${TARGET_FILE};     
        ${IS_LAST} && echo >> ${TARGET_FILE};
        echo "add";
        ;;
    *)
        mkdir -p "$(dirname ${TARGET_FILE})"
        pbpaste > ${TARGET_FILE};
        ${IS_LAST} && echo >> ${TARGET_FILE};
        echo "else";
        ;;
esac

if [[ ${EXT} = 'csv' ]]
then
    TMPCSV=$(replace-commas "${TARGET_FILE}")
    mv "${TMPCSV}" "${TARGET_FILE}"
fi
