#!/bin/zsh


_pipe-input-example-script () {
    IFS=${DELIMITER_ENDL}
    INP=($(get-stdin)) 
	echo "Input via Pipe \${#INP}=${#INP} ${INP}"
	echo "Input via Args \$#=$# or \${#@}=${#@} ${@} "
}
_pipe-input-example-script ${@}
