#!/bin/zsh


_removeFromPath2 () {
	[[ -d "${1}" ]] && PATH=$(echo $PATH | sed -E "s/${1//\//\/}://g")  || echo "${1} isn't a directory. Only directories can be a PATH element" > /dev/stderr
}
_removeFromPath2 ${@}
