#!/bin/zsh


_removeFromPath () {
	[[ -d "${1}" ]] && PATH=${PATH//${1}:/} || {
		echo Path\ should\ be\ a\ folder.\\nIf\ its\ part\ of\ the\ PATH\ variable\ remove\ it\ from\ the\ startup-sequence\ script\ where\ it\ gets\ set. > /dev/stderr
		retexit 1
	}
}
_removeFromPath ${@}
