#!/bin/zsh

cat <<-END >&2
###############################################################
# ${1}                                              #
#                                                             #
# Use this template as the beginning of a new program. Place  #
# a short description of the script here.                     #
#                                                             #
# Change History                                              #
# $(dateD.M.Y) Sedat Kilinc Original code. This is a template   #
# for creating new Bash shell                                 #
# scripts.                                                    #
# Add new history entries as needed.                          #
#                                                             #
#                                                             #
###############################################################
###############################################################
###############################################################
#                                                             #
# Copyright (C) $(dateYear), Sedat Kilinc                            #
# sedatkilinc05@gmail.com                                     #
#                                                             #
# This program is free software; you can redistribute it      #
# and/or modify it under the terms of the GNU General Public  #
# License as published by the Free Software Foundation;       #
# either version 2 of the License, or (at your option) any    #
# later version.                                              #
#                                                             #
# This program is distributed in the hope that it will be     #
# useful, but WITHOUT ANY WARRANTY; without even the implied  #
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR     #
# PURPOSE. See the GNU General Public License for more        #
# details.                                                    #
#                                                             #
# You should have received a copy of the GNU General Public   #
# License along with this program; if not, write to the Free  #
# Software Foundation, Inc., 59 Temple Place, Suite 330,      #
# Boston, MA 02111-1307 USA                                   #
#                                                             #
###############################################################
###############################################################
###############################################################
END
