#!/bin/zsh

SRCH_TYPE=''
SRCH_QUERY=''

while [[ $# -gt 0 ]]
do
    case "${1}" in
        --*=* || -*=*)
            optarg=$(echo "${1}" | sed -e 's/[-_a-zA-Z0-9]*=//')
            #echo "$1 optarg1 $optarg"
            ;;
        --* || -*)
            #optarg=$(echo "${2}" | sed -e 's/[-_a-zA-Z0-9]*=//')
            optarg=${2}
            #echo "$2 optarg2 $optarg"
            ;;
        *)
            optarg=${1}
            #echo "1: $1 optarg- $optarg"
            #echo "2: $2 optarg- $optarg"
            ;;
    esac

    case "${1}" in
         --user=* || -u=* || --user || -u)
             #SRCH_QUERY=$optarg
             [[ -z $SRCH_QUERY ]] && SRCH_QUERY="${optarg}"
             SRCH_TYPE=users
             ;;
         --topic=* || -T=* || --topic || -T)
             #SRCH_QUERY=$optarg
             [[ -z $SRCH_QUERY ]] && SRCH_QUERY="${optarg}"
             SRCH_TYPE=topics
             ;;
         --code=* || -c=* || --code || -c)
             #SRCH_QUERY=$optarg
             [[ -z $SRCH_QUERY ]] && SRCH_QUERY="${optarg}"
             SRCH_TYPE=code
             ;;
        --query=* || -q=* || --query || -q)
             SRCH_QUERY=$optarg
             ;;
        --type=* || -t=* || --type || -t)
             SRCH_TYPE=$optarg
             ;;
        --browser=* || -b=* || --browser || -b)
              BROWSER=$optarg
              ;;
         *)
             [[ -z $SRCH_QUERY ]] && SRCH_QUERY="${optarg}"
             [[ -n $SRCH_QUERY ]] && [[ -z $SRCH_TYPE ]] && SRCH_TYPE="${optarg}"
             ;;
     esac
     shift
done
$BROWSER "https://github.com/search?q=${SRCH_QUERY}&type=${SRCH_TYPE}"
