#!/bin/zsh

source ${SHELL_DEBUGSTATE}

usage "${0}" "$#" 2 '<searchterm> <path> [<number of lines after match> <number of lines before match>]' "returns search result with path and matching content" || . retexit $?

BEFORE=0
AFTER=0
CAT=cat
if  [[ -n "`which ccat`" ]]; then 
    CAT=ccat
fi
(isDebugLocal || isDebug) && echo "1. \${@} = ${@}"
if startsWith ${1} "-"
then
    GREP_OPTIONS="${1}"
    shift
fi

(isDebugLocal || isDebug) && printf "2. \${@} = ${@} \n $GREP_OPTIONS\n"

LOG="${TMP}/srcha/search_${1//\//•}.txt"
mkdir -p $(dirname ${LOG})

if isNumber ${3} || [[  ${3} -gt 0 ]]
then
    AFTER="-A ${3}"
fi

if [[ ${4} -gt 0 ]]
then
     BEFORE="-B ${4}"
fi


LOG_OUTPUT="${OUTPUT_SRCHA}/srcha•${1//\//${SLASH_DIVISION}}_${2//\//${SLASH_DIVISION}}_${BEFORE}_${AFTER}•$(date +'%s').txt"

if [[ -f "${2}" ]]
then
    (isDebugLocal || isDebug) && echo "${CAT} ${2} | grep -n ${GREP_OPTIONS} ${BEFORE} ${AFTER} ${1} "
    ${CAT} "${2}" | grep -n $GREP_OPTIONS "${1}" $BEFORE $AFTER 2> /dev/null | tee -a ${LOG_OUTPUT}
elif [[ -d "${2}" ]]
then
    (isDebugLocal || isDebug) && echo "grep -nRIs ${GREP_OPTIONS} \"${1}\" \"${2}\" ${BEFORE} ${AFTER}"
    grep -nRIs ${GREP_OPTIONS} "${1}" "${2}" ${BEFORE} ${AFTER} --exclude-dir .git 2> /dev/null | tee -a ${LOG_OUTPUT}
fi
