#!/bin/zsh

_set-flags-CPP-LD () {
	export CPPFLAGS=( ${CPPFLAGS} )
	export LDFLAGS=( ${LDFLAGS} )
	CPPFLAGS+="-I${PATH_CPP_FLAGS_INCLUDE}"
	LDFLAGS+="-L${PATH_LD_FLAGS_LIB}"
}

_set-flags-CPP-LD ${@}
