#!/bin/bash
sudo ifconfig lo0 10.0.0.1 alias
echo "rdr pass on lo0 inet proto tcp from any to 10.0.0.1 port 80 -> 127.0.0.1 port 3000" | sudo pfctl -ef -
if [ $? -eq 0 ]; then
    IF_ALIAS_10_0_0_1_80_TO_LO_3000_SET=1
fi

