#!/bin/bash

sha1_prod() {
    for f in "$(ls -d $1/*)"; 
    do 
        if [ -f "$f" ]; then 
            shasum $f 2> /dev/null;
        else 
            shasum $f/* 2> /dev/null;
        fi 
    done; 
}

sha1_test() {
     for f in "$(ls -d $1/*)";
     do
         isFile "$f" && {
             echo "is ne Datei";
             shasum $f;
         } || {
             echo "is keine Datei";
             shasum $f/*;
         }
     done;
}

OPERATIONPATH='.'

if [ -n "$1" ]; 
then
    OPERATIONPATH="$1"
else
    echo "No path given"
    echo "Current directory will be used"
fi


sha1_prod "$OPERATIONPATH"
