#!/bin/zsh

export ARR_SPLIT=() 

_split2arr () {
    while [[ $# -gt 0 ]]
    do
        [[ ${#1} -eq 1 ]] && DELIMITER="${1}" && shift
        [[ ${#1} -gt 1 ]] && STR2SPLIT="${1}" && shift
    done
	IFS=${DELIMITER_ENDL}
	for i in $(listit ${STR2SPLIT} ${DELIMITER})
	do
		[[ -n ${i} ]] && ARR_SPLIT+=("${i}") 
	done
    echo '${#ARR_SPLIT}='${#ARR_SPLIT}
}
_split2arr ${@}
