#!/usr/bin/env python3

import math
import sys

def square_root(num):
	return math.sqrt(num)

def goodfunc():
	print(square_root(10))

def badfunc():
	print (square_root("10"))


#badfunc()

#print(sys.argv[0])

if len(sys.argv) > 1:
	print(square_root(float(sys.argv[1])))
else:
	goodfunc()



