#!/bin/bash
echo '#######'
C=$#
echo ${@:$#:1}
echo ${@:0:$#}
echo '#######'
echo $2

FILES=($(ls ${@:0:$#}))

ARR=
DEL=––––––––––––––––––––––––––––––––––––––––

if [ -n $2 ]; then
    echo "not set"
fi

for ff in $FILES 
do 
    cat $ff
    echo $DEL
done
