#!/bin/zsh

STOP=$(timestamp)
#startsWithDash ${1:-NoDashParam} &&
#echo "${STOP}" > ${TMPDIR}/timer-stop-${@[-1]:-default}.txt

_timer-stop () {
	QUIET=false
	startsWithDash ${1:-NoDashParam} && [ ${1/-/} = 'q' -o ${1/-/} = '-quiet' ] && QUIET=true  && shift
    echo "${STOP}" > ${TMPDIR}/timer-stop-${1:-default}.txt
	#START=$(cat ${TMPDIR}/timer-start-${1:-default}.txt)
	#TIME_TOTAL=$((${STOP}-${START}))
	#${QUIET} || echo "Time Total ${TIME_TOTAL} seconds"
	${QUIET} && timer-result -v ${@} || timer-output ${1}
}

_timer-stop ${@}
