#!/bin/zsh

IFS=${DELIMITER_ENDL}
IS_HISTFILE=false
VERBOSE=false
[[ $# -gt 0 ]] && startsWithDash ${1} && ([[ ${1/-/} = 'H' ]] || [[ ${1/-/} = '-histfile' ]]) && IS_HISTFILE=true && shift
[[ $# -gt 0 ]] && startsWithDash ${1} && ([[ ${1/-/} = 'v' ]] || [[ ${1/-/} = '-verbose' ]]) && VERBOSE=true && shift
alias grepTimestampHistoryFile="grep -oE '^:\s?\d{10}:\d{1};' | grep -oE '\d{10}'"
alias grepTimestampAny="grep -oE '\d{10}'"

INPUT_STDIN=($(get-stdin &))
if [[ -n ${INPUT_STDIN} ]]
then
    for INPUT_ELEMENT in ${INPUT_STDIN}
    do
        ${IS_HISTFILE} && ARR_CURR_TS=($(echo ${INPUT_ELEMENT} | grepTimestampHistoryFile)) || ARR_CURR_TS=($(echo ${INPUT_ELEMENT} | grepTimestampAny))
        for CURR_TS in ${ARR_CURR_TS}
        do
            [[ -n $CURR_TS ]] && CURR_DATE=$(date -r ${CURR_TS}) || CURR_DATE=''
            INPUT_ELEMENT_DATE="${INPUT_ELEMENT/${CURR_TS}/${CURR_DATE}}"
        done
        if ${VERBOSE}
        then
            ${IS_HISTFILE} && echo "${INPUT_ELEMENT_DATE}" || echo "${INPUT_ELEMENT} ⟹   ${CURR_DATE}"
        else
            ${IS_HISTFILE} && echo "${INPUT_ELEMENT_DATE}" || echo "${CURR_DATE}"
        fi
    done
else

    [[ ${#@} -gt 0 ]] && TS="${1}" || TS="$(pbpaste)"

    isNumeric ${TS} && [[ ${#TS} -ge 10 ]] &&  date -r ${TS}
fi

