#!/bin/zsh



_trim () {
    IFS=${DELIMITER_ENDL}
    INPUT_PIPE=($(get-stdin&))
    #[[ -n ${INPUT_PIPE} ]] && ARR_LINES=(${INPUT_PIPE})
    for line in ${@:-${INPUT_PIPE}}
    do
        echo "${line}" | sed -E "s/(^[ ]+|[ ]+$)//g"    
    done
}
_trim ${@}
