#!/bin/bash
INDEX=0

if [ -n "$2" ];then
    INDEX="$2"
fi

curl -s http://api.urbandictionary.com/v0/define?term="$1" |  python3 -c 'import json,sys;obj=json.load(sys.stdin);print (obj["list"]['$INDEX']["definition"])' 2> /dev/null

ERRORR="$?"

if [ "$ERRORR" -gt 0 ] && [ -n "$2" ] && [ "$2" -gt 0 ]; then
    echo "out of range";
elif [ "$ERRORR" -gt 0 ]; then
    echo "error = $ERRORR"
    echo "no definition";
fi


