#!/usr/bin/env node

var processor = process.argv.shift()

var path2script = process.argv.shift()

var email = process.argv.shift()

/* **************************
 * **************************
 * *****		*****
 * ***** EMAIL VALID	*****
 * *****     OR		*****
 * *****  NOT  !!!	*****
 * *****		*****
 * **************************
 * **************************/

function match(email) {
	var match = /^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/.exec(email);
	return match;
}

function isEmailValid(email) {
	let m = match(email);
	return (m && m.length) || false;
}
/*
let email = 'sedat.kilinc@live.de';
console.log((isEmailValid(email)) ? match(email) : email + ' is invalid' );

email = 'sedat.kilinc@lüövä.dö';
console.log((isEmailValid(email)) ? match(email) : email + ' is invalid' );
*/

console.log((isEmailValid(email)) ? match(email) : email + ' is invalid' );

