#!/bin/zsh


_vtt2plain () {
	OUTPUTFILE="$(fileroot "${1}").txt" 
	cat_ "${1}" | sed -E "s/.*[0-9]{2}\:.*//g" > $TMP/no-timestamps.txt
	noduplicate $TMP/no-timestamps.txt "${OUTPUTFILE}"
	mv -i "${TMP}/${OUTPUTFILE}" "${PWD}"
}
_vtt2plain ${@}
