#!/bin/zsh

if [ $# -eq 0 ]; then
    echo "arguments missing"
    echo "Usage: $(basename $0) example.com"
    exit 1
fi

/Applications/Firefox\ Developer\ Edition.app/Contents/MacOS/firefox "https://www.wmtips.com/tools/info/$1"
