#!/bin/zsh

CMDNAME=${0##*/}

_find-scripts-named () {
    usage "${CMDNAME}" "$#" 1 '<scriptname> [<maxdepth>]' 'Searches $BIN for any script with the name passed in the 1st argument in the depth according to the 2nd argument' || return 6996 
    SCRIPTNAME="${1}"
    shift
    DEPTH=${1:-1}
    # shift
	find $BIN/ -name "${SCRIPTNAME}" -maxdepth ${DEPTH} # ${@}
}
_find-scripts-named ${@} | sed -E "s/${REGEX_TOO_MANY_SLASHES}/\//g"
