#!/bin/bash
if [ $# -gt 1 ]; then
    cd $2;
fi

ls $(echo "*$(echo $1 | cut -d= -f 2)*") 2> /dev/null
if [ $? -eq 1 ]; then 
     ls $(echo "*$(echo $1 | rev | cut -d - -f 1 | rev)*") 2> /dev/null
fi

