#!/bin/zsh


_zsh-tmux-run () {
	if [[ -n "$@" ]]
	then
		command tmux "$@"
		return $?
	fi
	local -a tmux_cmd
	tmux_cmd=(command tmux) 
	[[ "$ZSH_TMUX_ITERM2" == "true" ]] && tmux_cmd+=(-CC) 
	[[ "$ZSH_TMUX_UNICODE" == "true" ]] && tmux_cmd+=(-u) 
	if [[ -n "$ZSH_TMUX_DEFAULT_SESSION_NAME" ]]
	then
		[[ "$ZSH_TMUX_AUTOCONNECT" == "true" ]] && $tmux_cmd attach -t $ZSH_TMUX_DEFAULT_SESSION_NAME
	else
		[[ "$ZSH_TMUX_AUTOCONNECT" == "true" ]] && $tmux_cmd attach
	fi
	if [[ $? -ne 0 ]]
	then
		if [[ "$ZSH_TMUX_FIXTERM" == "true" ]]
		then
			tmux_cmd+=(-f "$_ZSH_TMUX_FIXED_CONFIG") 
		elif [[ -e "$ZSH_TMUX_CONFIG" ]]
		then
			tmux_cmd+=(-f "$ZSH_TMUX_CONFIG") 
		fi
		if [[ -n "$ZSH_TMUX_DEFAULT_SESSION_NAME" ]]
		then
			$tmux_cmd new-session -s $ZSH_TMUX_DEFAULT_SESSION_NAME
		else
			$tmux_cmd new-session
		fi
	fi
	if [[ "$ZSH_TMUX_AUTOQUIT" == "true" ]]
	then
		exit
	fi
}
_zsh-tmux-run ${@}
